### ISSUE TITLE
ValueError Bug

### ISSUE THREAD

**Issue by mdeggies** [rdegges/stormpath-export#6] opened 2016-10-13 20:53 UTC
I saw this bug during testing that springs up on line 171 when setting the type of the default account store mapping: 

`'type': application.default_account_store_mapping.account_store.__class__.__name__`

```
=== Exporting all application data...
- Exporting application: ADFS Tester
Traceback (most recent call last):
  File "stormpath-export.py", line 610, in <module>
    main()
  File "stormpath-export.py", line 606, in main
    exporter.export(arguments['<location>'])
  File "stormpath-export.py", line 545, in export
    getattr(self, 'export_' + export_type)()
  File "stormpath-export.py", line 171, in export_applications
    'type': application.default_account_store_mapping.account_store.__class__.__name__,
  File "/usr/local/lib/python2.7/site-packages/stormpath/resources/base.py", line 129, in __getattr__
    self._ensure_data()
  File "/usr/local/lib/python2.7/site-packages/stormpath/resources/base.py", line 273, in _ensure_data
    self._set_properties(data, overwrite=overwrite)
  File "/usr/local/lib/python2.7/site-packages/stormpath/resources/base.py", line 177, in _set_properties
    value = self._wrap_resource_attr(resource_attrs[name], value)
  File "/usr/local/lib/python2.7/site-packages/stormpath/resources/base.py", line 144, in _wrap_resource_attr
    return cls(self._client, properties=value)
  File "/usr/local/lib/python2.7/site-packages/stormpath/resources/account_store.py", line 30, in AccountStore
    href)
ValueError: AccountStore called for non-account store href directories/$DIRECTORY_ID
```

**Comment by rdegges** [comment] 2016-10-20 01:26
Going to close this since we couldn't reproduce. If you do run into this again, please open a new issue and include some of your tenant info so I can reproduce ^^ Thanks <33

**Closed as completed by rdegges** 2016-10-20 01:26 UTC
